spring:
  application:
    name: expensense-control
  data:
    mongodb:
#      uri: ${MONGO_URI}
      uri: mongodb://localhost:27017/expenses-control

logging:
  level:
    org:
      springframework:
        security: DEBUG
#    root: ${LOG_LEVEL}
#    root: DEBUG

environment:
  config:
    token-expiration: 36000
#    secret-key: ${SECRET_KEY}
    secret-key: 12345678901234567890123456789012

server:
  port: 7000
